[project]
name = "found"
version = "0.1.0"
dependencies = ["anndata", "scikit-learn", "scanpy", "pandas"]

[project.optional-dependencies]
dev = [
    "sphinx",
    "pydata-sphinx-theme",
    "myst-nb",
    "myst-parser",
    "sphinx-autobuild",
    "jupytext",
    "seaborn",
    "ipykernel",
    "sphinx-autodoc-typehints",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
