[project]
name = "found"
version = "0.1.0"
dependencies = [
    "anndata>=0.12",
    "scikit-learn",
    "scipy",
    "numpy",
    "altair[all]",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-autodoc-typehints",
    "pydata-sphinx-theme",
    "myst-nb",
    "myst-parser",
    "jupytext",
    "ipykernel",
    "ipywidgets",
    "scanpy[leiden]",
    "scikit-misc",
    "pandas",
    "pyLemur",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
