from typing import Any

import anndata as ad
import numpy as np
import pandas as pd

from .adapters import Pipeline
from .methods import kmeans_bin, log_reg, run_lognorm_pca
from .tune import FixPointTuner, Tuner
from .types import BoolArr, NumArr


def remap[T: np.ndarray[tuple[int], Any]](adj_bool: BoolArr, orig_label: T | pd.Series, control_val: Any) -> T:
    return np.where(adj_bool, orig_label, control_val)  # pyright: ignore
    # ignore NECESSITY - np.where broadcasting does
    # not maintain array size in type information


def HiDDEN(
    x: ad.AnnData,
    cond_col: str,
    control_val: Any,
    algo: Pipeline = Pipeline(run_lognorm_pca, log_reg, kmeans_bin, True),
    **kwargs,
) -> tuple[NumArr, np.ndarray[tuple[int], Any]]:
    """
    runs HiDDEN on a given :py:class:`~anndata.AnnData` object.

    :param adata: input :py:class:`~anndata.AnnData` object
    :param cond_col: string indicating obs column in adata representing condition value
    :param control_val: value representing the control condition in the provided condition column
    :param algo: algorithm pipeline (expected to use parameter ``V`` as original condition annotation)
    :param kwargs: additional variables to pass into pipeline
    :return: 2-tuple consisting of:

        - 1-d array of prediction outputs by model
        - binarized labels from prediction values
    """

    y_hat, new_ann, _ = algo(V=(x.obs[cond_col] != control_val).to_numpy(), **kwargs)

    return (
        y_hat,
        remap(
            new_ann,
            x.obs[cond_col],  # pyright: ignore
            control_val,
        ),
    )


def HiDDENt[P, S](
    x: ad.AnnData,
    cond_col: str,
    control_val: Any,
    algo: Pipeline = Pipeline(run_lognorm_pca, log_reg, kmeans_bin, True),
    tuner: Tuner[P, S] = FixPointTuner(5, 8, 0.04),
    **kwargs,
) -> tuple[P, dict[P, tuple[NumArr, np.ndarray[tuple[int], Any], S]]]:
    """
    runs HiDDEN on a given :py:class:`~anndata.AnnData` object, trying to optimize for a specific set of dimensions using provided :py:class:`~found.tune.Tuner`.

    :param adata: input :py:class:`~anndata.AnnData` object
    :param cond_col: string indicating obs column in adata representing condition value
    :param control_val: value representing the control condition in the provided condition column
    :param algo: algorithm pipeline (expected to use parameter ``V`` as original condition annotation)
    :param tuner: provided tuner which attempts to optimize pipeline for a specific hyperparameter
    :param kwargs: additional variables to pass into pipeline
    :return: 2-tuple consisting of:

        - selected optimal pipeline hyperparameters
        - dictionary with keys being attempted pipeline hyperparameters and values being a 3-tuple of:
            - 1-d array of prediction outputs by model
            - model adjusted labels
            - optional scoring value generated by tuner for specific hyperparameter configuration

    """

    best_k, outs = tuner(algo, V=(x.obs[cond_col] != control_val).to_numpy(), **kwargs)

    return (
        best_k,
        {
            k: (
                Y,
                remap(
                    W,
                    x.obs[cond_col],  # pyright: ignore
                    control_val,
                ),
                s,
            )
            for k, (Y, W, s) in outs.items()
        },
    )
