
from typing import Any

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.cluster import KMeans
from sklearn.neighbors import NearestCentroid, RadiusNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from .adapters import step_fn
from .seed import get_seed
from .types import BoolArr, FloatMtx, NumArr
from .methods import HasFitBinClass





@step_fn("Y", "model")
def reg_gp_multi(
    Z: FloatMtx,
    V: NumArr,
    gp_args: dict[str, Any] | None = None,
) -> tuple[NumArr, GaussianProcessClassifier]:
    """
    runs a Gaussian process classifier -based regression to score cells as one of a multitude of classes.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d numerical array of condition labels
    :param gp_args: additional arguments to pass to :py:class:`~sklearn.gaussian_process.GaussianProcessClassifier`
    :return: 2-tuple of:

        - n-d float array of probability scores generated by the fitted model
        - the fitted model object
    """
    # print(Z, V)

    return sklearn_wrap_multiclass(
        Z,
        V,
        GaussianProcessClassifier(
            random_state=get_seed(),
            **(gp_args or {}),
        ),
    )


@step_fn("Y", "model")
def reg_lr_multi(
    Z: FloatMtx,
    V: NumArr,
    gp_args: dict[str, Any] | None = None,
) -> tuple[NumArr, GaussianProcessClassifier]:
    """
    runs logistic regression to score cells as one of a multitude of classes.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d numerical array of condition labels
    :param gp_args: additional arguments to pass to :py:class:`~sklearn.linear_model.LogisticRegression`
    :return: 2-tuple of:
        - n-d float array of probability scores generated by the fitted model
        - the fitted model object
    """

    return sklearn_wrap_multiclass(
        Z,
        V,
        LogisticRegression(
            random_state=get_seed(),
            **(gp_args or {}),
        ),
    )


@step_fn("Y", "model")
def reg_rf_multi(
    Z: FloatMtx,
    V: NumArr,
    rf_args: dict[str, Any] | None = None,
) -> tuple[NumArr, RandomForestClassifier]:
    """
    runs a random forest classifier -based regression to score cells as affected/unaffected by the condition.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d boolean array of condition labels (False corresponds to control, True to case)
    :param rf_args: additional arguments to pass to :py:class:`~sklearn.ensemble.RandomForestClassifier`
    :return: 2-tuple of:

        - 1-d float array of probability scores generated by the fitted model
        - the fitted model object
    """

    return sklearn_wrap_multiclass(
        Z,
        V,
        RandomForestClassifier(
            random_state=get_seed(),
            **(rf_args or {}),
        ),
    )


@step_fn("Y", "model")
def reg_svm_multi(
    Z: FloatMtx,
    V: NumArr,
    svm_args: dict[str, Any] | None = None,
) -> tuple[NumArr, SVC]:
    """
    runs a support vector machine classifier -based regression to score cells as affected/unaffected by the condition.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d boolean array of condition labels (False corresponds to control, True to case)
    :param svm_args: additional arguments to pass to :py:class:`~sklearn.svm.SVC`
    :return: 2-tuple of:

        - 1-d float array of probability scores generated by the fitted model
        - the fitted model object
    """
    return sklearn_wrap_multiclass(
        Z,
        V,
        SVC(
            probability=True,
            random_state=get_seed(),
            **(svm_args or {}),
        ),
    )

@step_fn("Y", "model")
def reg_nc_multi(
    Z: FloatMtx,
    V: NumArr,
    nc_args: dict[str, Any] | None = None,
) -> tuple[NumArr, SVC]:
    """
    runs a Nearest Centroid classifier -based regression to score cells as affected/unaffected by the condition.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d boolean array of condition labels (False corresponds to control, True to case)
    :param svm_args: additional arguments to pass to :py:class:`~sklearn.neighbors.NearestCentroid`
    :return: 2-tuple of:
        - 1-d float array of probability scores generated by the fitted model
        - the fitted model object
    """
    return sklearn_wrap_multiclass(
        Z,
        V,
        NearestCentroid(
            **(nc_args or {}),
        ),
    )


@step_fn("Y", "model")
def reg_rn_multi(
    Z: FloatMtx,
    V: NumArr,
    nc_args: dict[str, Any] | None = None,
) -> tuple[NumArr, SVC]:
    """
    runs a Radius Neighbors Classifier to score cells as affected/unaffected by the condition.

    :param Z: cell by k matrix (where k is some number of dimensions)
    :param V: 1-d boolean array of condition labels (False corresponds to control, True to case)
    :param svm_args: additional arguments to pass to :py:class:`~sklearn.neighbors.RadiusNeighborsClassifier`
    :return: 2-tuple of:
        - 1-d float array of probability scores generated by the fitted model
        - the fitted model object
    """
    return sklearn_wrap_multiclass(
        Z,
        V,
        RadiusNeighborsClassifier(
            **(nc_args or {}),
        ),
    )


def bin_argmax_multiclass(
    Y: FloatMtx,
) -> FloatMtx:
    """
    A stub function for multiclass binarization.
    simply returns the index of the highest scoring class for each sample.

    :param Y: n-d float array of probability scores
    :return: 1-d float array of binarized scores
    """

    # return the index of the highest percentaqe class for each sample in Y
    max = np.argmax(Y, axis=1)

    return max

def bin_kmeans_mean_multiclass(
    Y: FloatMtx,
    n_clusters: int | None = None,
) -> FloatMtx:
    """
    A k-means based binarization function for multiclass classification.
    assigns each sample to a cluster based on k-means clustering of the scores.

    :param Y: n-d float array of probability scores
    :param n_clusters: number of clusters to use for k-means. If None, inferred from the number of columns in Y.
    :return: 1-d float array of binarized scores
    """

    if n_clusters is None:
        n_clusters = Y.shape[1]

    kmeans = KMeans(n_clusters=n_clusters, random_state=get_seed())
    cluster_labels = kmeans.fit_predict(Y)

    # Map each cluster to the index of the highest scoring class in that cluster
    cluster_to_class = {}

    for cluster_id in range(n_clusters):
        # indices of samples in this cluster
        idx = np.where(cluster_labels == cluster_id)[0]

        if len(idx) == 0:
            # Handle empty clusters: just map to a dummy class (e.g., argmax of centroid)
            class_id = np.argmax(kmeans.cluster_centers_[cluster_id])
        else:
            # Compute mean class-score vector for the cluster
            mean_vec = Y[idx].mean(axis=0)
            # Assign cluster to the class with highest mean score
            class_id = np.argmax(mean_vec)

        cluster_to_class[cluster_id] = class_id
    # print(cluster_to_class)
    # Map every sample's cluster → class
    final_labels = np.array([cluster_to_class[c] for c in cluster_labels], dtype=int)

    return final_labels



def bin_kmeans_centroid_multiclass(
    Y: FloatMtx,
    n_clusters: int | None = None,
) -> FloatMtx:
    """
    A k-means based binarization function for multiclass classification.
    assigns each sample to a cluster based on k-means clustering of the scores.

    :param Y: n-d float array of probability scores
    :param n_clusters: number of clusters to use for k-means. If None, inferred from the number of columns in Y.
    :return: 1-d float array of binarized scores
    """

    if n_clusters is None:
        n_clusters = Y.shape[1]

    kmeans = KMeans(n_clusters=8, random_state=get_seed())
    cluster_labels = kmeans.fit_predict(Y)

    # Map each cluster to the index of the highest scoring class in that cluster
    cluster_to_class = {}

    for cluster_id in range(8):
        # indices of samples in this cluster
        idx = np.where(cluster_labels == cluster_id)[0]

        if len(idx) == 0:
            # Handle empty clusters: just map to a dummy class (e.g., argmax of centroid)
            class_id = np.argmax(kmeans.cluster_centers_[cluster_id])
        else:
            # Get the cluster's centroid (the k-means computed center)
            centroid = kmeans.cluster_centers_[cluster_id]
            # Find the class with the highest probability in the centroid
            class_id = np.argmax(centroid)

        cluster_to_class[cluster_id] = class_id

    # print(cluster_to_class)
    # Map every sample's cluster → class
    final_labels = np.array([cluster_to_class[c] for c in cluster_labels], dtype=int)

    return final_labels


def sklearn_wrap_multiclass[T: HasFitBinClass](Z: FloatMtx, V: NumArr, model: T) -> tuple[NumArr, T]:
    # As sklearn_wrap, but for multiclass classification
    model = model.fit(Z, V)

    return (
        model.predict_proba(Z),
        model,
    )